"use client";

import Link from "next/link";
import { use, useState } from "react";
import { useDemo } from "@/components/DemoProvider";
import { AppShell, EmptyState, EvidenceCard, LongevityScore, ProductCard, ProductVisual, RepairabilityBadge, ScoreBreakdown, SustainabilityBadge } from "@/components/ui";

export default function ProductDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { products, notify } = useDemo();
  const [galleryIndex, setGalleryIndex] = useState(0);
  const [saved, setSaved] = useState(false);
  const product = products.find((item) => item.id === id && item.status === "approved");

  if (!product) return <AppShell><div className="page-shell py-24"><EmptyState title="Product not found" text="This product may not be approved yet, or the link may be invalid." action={<Link className="button-primary" href="/search">Browse approved products</Link>} /></div></AppShell>;
  const related = products.filter((item) => item.status === "approved" && item.id !== product.id && item.category === product.category).slice(0, 3);
  const fallbackRelated = related.length ? related : products.filter((item) => item.status === "approved" && item.id !== product.id).slice(0, 3);

  return <AppShell><div className="page-shell py-8"><nav className="flex flex-wrap gap-2 text-sm text-slate-500" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/search">Products</Link><span>/</span><span className="text-slate-900">{product.name}</span></nav>
    <section className="mt-8 grid gap-10 lg:grid-cols-[1.04fr_.96fr]"><div><div className="rounded-3xl border border-slate-200 bg-white p-4"><ProductVisual product={product} /><p className="mt-3 text-center text-xs text-slate-400">Product visual {galleryIndex + 1} of {product.imageUrls.length}</p></div><div className="mt-3 flex gap-3">{product.imageUrls.map((image, index) => <button key={image} onClick={() => setGalleryIndex(index)} aria-label={`View product image ${index + 1}`} className={`h-20 w-24 rounded-2xl border bg-gradient-to-br ${product.visualTone} text-2xl font-black ${galleryIndex === index ? "border-emerald-700 ring-2 ring-emerald-200" : "border-slate-200"}`}>{product.visual}</button>)}</div></div>
      <div><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">{product.brand} · {product.category}</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">{product.name}</h1>{product.price && <p className="mt-4 text-xl font-black">${product.price.toLocaleString("en-AU")} AUD</p>}</div><LongevityScore score={product.longevityScore} size="lg" /></div><p className="mt-7 text-base leading-7 text-slate-600">{product.description}</p><div className="mt-5 flex flex-wrap gap-2"><RepairabilityBadge score={product.repairabilityScore} />{product.certifications.length > 0 && <SustainabilityBadge />}<span className="badge bg-sky-50 text-sky-800">{product.evidenceConfidence} confidence</span></div>
        <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[`${product.expectedLifespanYears} yrs`, "Expected life"], [`${product.warrantyYears} yrs`, "Warranty"], [product.repairAvailable ? "Available" : "Limited", "Repairs"], [product.replacementPartsAvailable ? "Available" : "Limited", "Parts"]].map(([value, label]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4"><strong className="block">{value}</strong><span className="mt-1 block text-xs text-slate-500">{label}</span></div>)}</div>
        <div className="mt-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="font-black text-emerald-950">Why Evermark recommends it</h2><p className="mt-2 text-sm leading-6 text-emerald-900/75">This product combines a long expected service life with accessible repairs and replacement parts. Its score is based on company-submitted information and the verified demo evidence shown below—not independent laboratory testing.</p></div>
        <div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href={product.officialUrl} target="_blank" rel="noreferrer" className="button-primary flex-1">Buy from official website ↗</a><button onClick={() => { setSaved(!saved); notify(saved ? "Removed from saved products." : "Product saved for later.", "info"); }} className="button-secondary flex-1">{saved ? "✓ Saved" : "♡ Save product"}</button></div>
      </div></section>

    <section className="mt-20 grid gap-8 lg:grid-cols-2"><div className="card p-6 sm:p-8"><h2 className="text-2xl font-black tracking-[-.03em]">Longevity Score breakdown</h2><p className="mt-2 text-sm leading-6 text-slate-500">Weighted indicators derived from submitted and reviewed evidence.</p>{product.scoreBreakdown && <div className="mt-8"><ScoreBreakdown scores={product.scoreBreakdown} /></div>}</div><div className="card p-6 sm:p-8"><h2 className="text-2xl font-black tracking-[-.03em]">Materials & certifications</h2><div className="mt-7"><h3 className="text-xs font-black uppercase tracking-wider text-slate-500">Materials</h3><div className="mt-3 flex flex-wrap gap-2">{product.materials.map((material) => <span key={material} className="rounded-full bg-slate-100 px-3 py-2 text-sm font-semibold">{material}</span>)}</div></div><div className="mt-8"><h3 className="text-xs font-black uppercase tracking-wider text-slate-500">Certifications</h3>{product.certifications.length ? <div className="mt-3 flex flex-wrap gap-2">{product.certifications.map((cert) => <span key={cert} className="rounded-full bg-lime-50 px-3 py-2 text-sm font-semibold text-lime-800">✓ {cert}</span>)}</div> : <p className="mt-3 text-sm text-slate-500">No sustainability certifications submitted.</p>}</div></div></section>

    <section className="mt-20"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Evidence confidence: {product.evidenceConfidence}</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em]">Sources reviewed</h2></div></div><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{product.evidence.map((evidence) => <EvidenceCard key={evidence.id} evidence={evidence} />)}</div></section>
    <section className="py-20"><h2 className="text-3xl font-black tracking-[-.04em]">Related durable products</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{fallbackRelated.map((item) => <ProductCard key={item.id} product={item} />)}</div></section>
  </div></AppShell>;
}
