"use client";

import { useMemo, useState } from "react";
import ConfirmationModal from "@/components/ConfirmationModal";
import ValidationChecklist, { validationItems } from "@/components/ValidationChecklist";
import { useDemo } from "@/components/DemoProvider";
import { AppShell, EvidenceCard, LongevityScore, ProductVisual, RoleNotice, SearchBar, StatusBadge, StatusExplanation } from "@/components/ui";
import { categories } from "@/data/mock-products";
import type { ProductStatus } from "@/types";

type Decision = "approved" | "rejected" | "more_evidence_required";

export default function ValidatorPage() {
  const { products, updateStatus, notify } = useDemo();
  const [selectedId, setSelectedId] = useState(products.find((p) => p.status === "pending")?.id ?? products[0]?.id);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | ProductStatus>("pending");
  const [category, setCategory] = useState("All");
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const [notes, setNotes] = useState("");
  const [decision, setDecision] = useState<Decision | null>(null);
  const selected = products.find((product) => product.id === selectedId);
  const list = useMemo(() => products.filter((product) => status === "all" || product.status === status).filter((product) => category === "All" || product.category === category).filter((product) => `${product.name} ${product.brand} ${product.company}`.toLowerCase().includes(query.toLowerCase())), [products, status, category, query]);
  const counts = { pending: products.filter((p) => p.status === "pending").length, approved: products.filter((p) => p.status === "approved").length, rejected: products.filter((p) => p.status === "rejected").length, evidence: products.filter((p) => p.status === "more_evidence_required").length };
  const checkCount = validationItems.filter((item) => checked[item]).length;
  const completeDecision = (reason?: string) => { if (!selected || !decision) return; updateStatus(selected.id, decision, reason || notes || undefined); notify(decision === "approved" ? `${selected.name} approved and published.` : decision === "rejected" ? `${selected.name} rejected.` : `Evidence request sent for ${selected.name}.`, decision === "rejected" ? "danger" : "success"); setDecision(null); setChecked({}); setNotes(""); };

  return <AppShell><section className="border-b border-slate-200 bg-white"><div className="page-shell py-9"><RoleNotice allowed={["validator"]}>Validators will use invite-only accounts in production.</RoleNotice><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Validator portal</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Evidence review queue</h1><p className="mt-3 text-slate-500">Review product claims consistently and record an auditable decision.</p></div></section>
    <div className="page-shell py-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[counts.pending, "Pending review", "bg-amber-50 text-amber-950"], [counts.evidence, "More evidence", "bg-orange-50 text-orange-950"], [counts.approved, "Approved", "bg-emerald-50 text-emerald-950"], [counts.rejected, "Rejected", "bg-red-50 text-red-950"]].map(([value, label, tone]) => <div key={String(label)} className={`rounded-2xl p-5 ${tone}`}><strong className="text-3xl">{value}</strong><p className="mt-2 text-sm font-bold opacity-70">{label}</p></div>)}</div>
      <div className="mt-7 grid gap-6 xl:grid-cols-[390px_1fr]"><aside className="card h-fit overflow-hidden xl:sticky xl:top-24"><div className="border-b border-slate-200 p-5"><SearchBar value={query} onChange={setQuery} placeholder="Search submissions…" /><div className="mt-3 grid grid-cols-2 gap-3"><select className="input text-sm" value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="more_evidence_required">More evidence</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><select className="input text-sm" value={category} onChange={(e) => setCategory(e.target.value)}><option>All</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="max-h-[700px] overflow-y-auto">{list.length ? list.map((product) => <button key={product.id} onClick={() => { setSelectedId(product.id); setChecked({}); }} className={`w-full border-b border-slate-100 p-5 text-left transition hover:bg-slate-50 ${selectedId === product.id ? "bg-emerald-50" : "bg-white"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-black">{product.name}</p><p className="mt-1 text-xs text-slate-500">{product.company} · {product.category}</p></div><StatusBadge status={product.status} /></div><p className="mt-3 text-xs text-slate-500">Submitted {product.submittedAt}</p></button>) : <div className="p-8 text-center text-sm text-slate-500">No submissions match these filters.</div>}</div></aside>
        {selected ? <section className="card overflow-hidden"><div className="border-b border-slate-200 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="flex flex-wrap gap-2"><StatusBadge status={selected.status} /><span className="badge bg-sky-50 text-sky-800">{selected.evidenceConfidence ?? "Low"} confidence</span></div><h2 className="mt-4 text-3xl font-black tracking-[-.04em]">{selected.name}</h2><p className="mt-2 text-sm text-slate-500">{selected.brand} · submitted by {selected.company}</p><StatusExplanation product={selected} /></div><LongevityScore score={selected.longevityScore ?? 78} size="lg" /></div></div>
          <div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[1fr_320px]"><div><ProductVisual product={selected} compact /><h3 className="mt-7 text-lg font-black">Product information</h3><p className="mt-3 text-sm leading-6 text-slate-600">{selected.description}</p><dl className="mt-5 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2">{[["Company", selected.company], ["Category", selected.category], ["Expected lifespan", `${selected.expectedLifespanYears ?? "—"} years`], ["Warranty", `${selected.warrantyYears ?? "—"} years`], ["Repair service", selected.repairAvailable ? "Available" : "Not available"], ["Replacement parts", selected.replacementPartsAvailable ? "Available" : "Not available"], ["Materials", selected.materials.join(", ") || "Not supplied"], ["Sustainability", selected.certifications.join(", ") || "No certifications"]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl><div className="mt-6 flex flex-wrap gap-3"><a href={selected.officialUrl} target="_blank" rel="noreferrer" className="button-secondary">Official website ↗</a>{selected.warrantyUrl && <a href={selected.warrantyUrl} target="_blank" rel="noreferrer" className="button-secondary">Warranty ↗</a>}{selected.repairPolicyUrl && <a href={selected.repairPolicyUrl} target="_blank" rel="noreferrer" className="button-secondary">Repair policy ↗</a>}</div>
              <h3 className="mt-9 text-lg font-black">Uploaded evidence</h3>{selected.evidence.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{selected.evidence.map((item) => <EvidenceCard key={item.id} evidence={item} />)}</div> : <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>Missing evidence:</strong> No supporting files or source links were submitted.</div>}
            </div><aside><div className="rounded-2xl bg-slate-50 p-5"><ValidationChecklist checked={checked} onChange={(item, value) => setChecked((current) => ({ ...current, [item]: value }))} /><p className="mt-3 text-xs text-slate-500">{checkCount} of {validationItems.length} checks completed</p></div><label className="mt-5 grid gap-2 text-sm font-black">Validator notes<textarea className="input font-normal" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Record observations, risks, or follow-up…" /></label>{selected.status === "pending" ? <div className="mt-6 grid gap-3"><button className="button-primary" onClick={() => setDecision("approved")}>Approve product</button><button className="button-secondary" onClick={() => setDecision("more_evidence_required")}>Request more evidence</button><button className="min-h-11 rounded-xl border border-red-200 bg-red-50 px-4 text-sm font-black text-red-700 hover:bg-red-100" onClick={() => setDecision("rejected")}>Reject product</button><p className="text-xs leading-5 text-slate-500">Approval publishes the product to public search. Rejection and evidence requests require a written reason.</p></div> : <div className="mt-6 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600">This submission already has a decision. Select a pending submission to take action.</div>}</aside></div>
        </section> : <div className="card grid min-h-96 place-items-center p-8 text-center text-slate-500">Select a submission to begin review.</div>}</div></div>{decision && selected && <ConfirmationModal action={decision} productName={selected.name} onClose={() => setDecision(null)} onConfirm={completeDecision} />}
  </AppShell>;
}
