"use client";

import { useState } from "react";
import { useDemo } from "@/components/DemoProvider";
import { categories } from "@/data/mock-products";
import type { Product, SubmissionFormData } from "@/types";

const emptyForm: SubmissionFormData = { brand: "", name: "", category: "", description: "", officialUrl: "", price: "", lifespan: "", warranty: "", warrantyUrl: "", repairPolicyUrl: "", repairAvailable: false, replacementPartsAvailable: false, materials: "", certifications: "", claims: "", imageFilename: "", evidenceFilename: "", evidenceType: "Warranty", evidenceUrl: "" };
const steps = ["Basic information", "Longevity & repair", "Materials", "Images & evidence", "Review & submit"];

export default function ProductSubmissionForm({ onComplete }: { onComplete: () => void }) {
  const { addProduct, notify } = useDemo();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<SubmissionFormData>(emptyForm);
  const [errors, setErrors] = useState<string[]>([]);
  const update = <K extends keyof SubmissionFormData>(key: K, value: SubmissionFormData[K]) => setForm((current) => ({ ...current, [key]: value }));
  const requiredForStep = () => step === 0 ? [form.brand, form.name, form.category, form.description, form.officialUrl] : step === 1 ? [form.lifespan, form.warranty] : step === 2 ? [form.materials] : [];
  const next = () => { if (requiredForStep().some((value) => !String(value).trim())) { setErrors(["Complete all required fields before continuing."]); return; } setErrors([]); setStep((current) => Math.min(4, current + 1)); };

  const makeProduct = (status: "draft" | "pending"): Product => ({
    id: `${form.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "submission"}-${Date.now()}`,
    name: form.name || "Untitled product", brand: form.brand || "Unspecified brand", company: "Northstar Product Co.", category: form.category || "Other", description: form.description || "Draft product submission", price: form.price ? Number(form.price) : undefined,
    imageUrls: form.imageFilename ? [form.imageFilename] : ["front"], visual: "◇", visualTone: "from-emerald-100 to-cyan-200", officialUrl: form.officialUrl || "https://example.com", expectedLifespanYears: form.lifespan ? Number(form.lifespan) : undefined, warrantyYears: form.warranty ? Number(form.warranty) : undefined,
    warrantyUrl: form.warrantyUrl || undefined, repairPolicyUrl: form.repairPolicyUrl || undefined, repairAvailable: form.repairAvailable, replacementPartsAvailable: form.replacementPartsAvailable,
    materials: form.materials.split(",").map((item) => item.trim()).filter(Boolean), certifications: form.certifications.split(",").map((item) => item.trim()).filter(Boolean), evidenceConfidence: "Low", evidence: form.evidenceFilename || form.evidenceUrl ? [{ id: `ev-${Date.now()}`, type: form.evidenceType, title: form.evidenceFilename || "Submitted source", filename: form.evidenceFilename || undefined, sourceUrl: form.evidenceUrl || undefined }] : [], status, submittedAt: new Date().toISOString().slice(0, 10),
  });
  const save = (status: "draft" | "pending") => { if (status === "pending" && (!form.name || !form.brand || !form.category)) { setErrors(["Brand, product name, and category are required to submit."]); return; } addProduct(makeProduct(status)); notify(status === "pending" ? "Product submitted and added to the validator queue." : "Draft saved to your submission history.", status === "pending" ? "success" : "info"); setForm(emptyForm); onComplete(); };

  const field = (label: string, key: keyof SubmissionFormData, type = "text", required = false, placeholder = "") => <label className="grid gap-2 text-sm font-bold">{label}{required && <span className="sr-only"> required</span>}<input className="input font-normal" type={type} required={required} value={String(form[key])} placeholder={placeholder} onChange={(e) => update(key, e.target.value as never)} /></label>;

  return <div><div className="mb-8 overflow-x-auto"><ol className="flex min-w-[680px] items-start">{steps.map((label, index) => <li key={label} className="flex flex-1 items-start"><button type="button" onClick={() => index < step && setStep(index)} className="group text-left" disabled={index > step}><span className={`grid h-9 w-9 place-items-center rounded-full text-sm font-black ${index <= step ? "bg-emerald-800 text-white" : "bg-slate-100 text-slate-400"}`}>{index < step ? "✓" : index + 1}</span><span className={`mt-2 block max-w-28 text-xs font-bold ${index <= step ? "text-slate-900" : "text-slate-400"}`}>{label}</span></button>{index < steps.length - 1 && <span className={`mt-4 h-px flex-1 ${index < step ? "bg-emerald-700" : "bg-slate-200"}`} />}</li>)}</ol></div>
    {errors.length > 0 && <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{errors.join(" ")}</div>}
    <div className="min-h-[390px]">
      {step === 0 && <div className="grid gap-5 sm:grid-cols-2">{field("Brand name", "brand", "text", true, "e.g. Northstar")}{field("Product name", "name", "text", true, "e.g. Field Pack 28L")}<label className="grid gap-2 text-sm font-bold">Category<select className="input font-normal" value={form.category} onChange={(e) => update("category", e.target.value)}><option value="">Select category</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></label>{field("Product price (AUD)", "price", "number", false, "299")}<label className="grid gap-2 text-sm font-bold sm:col-span-2">Description<textarea className="input font-normal" required value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="Describe the product and what makes it durable." /></label><div className="sm:col-span-2">{field("Official product URL", "officialUrl", "url", true, "https://")}</div></div>}
      {step === 1 && <div className="grid gap-5 sm:grid-cols-2">{field("Expected lifespan (years)", "lifespan", "number", true, "10")}{field("Warranty period (years)", "warranty", "number", true, "5")}{field("Warranty URL", "warrantyUrl", "url", false, "https://")}{field("Repair policy URL", "repairPolicyUrl", "url", false, "https://")}<label className="flex gap-3 rounded-2xl border border-slate-200 p-4 text-sm font-bold"><input type="checkbox" className="accent-emerald-700" checked={form.repairAvailable} onChange={(e) => update("repairAvailable", e.target.checked)} />Repair service available</label><label className="flex gap-3 rounded-2xl border border-slate-200 p-4 text-sm font-bold"><input type="checkbox" className="accent-emerald-700" checked={form.replacementPartsAvailable} onChange={(e) => update("replacementPartsAvailable", e.target.checked)} />Replacement parts available</label></div>}
      {step === 2 && <div className="grid gap-5"><label className="grid gap-2 text-sm font-bold">Materials<textarea className="input font-normal" value={form.materials} onChange={(e) => update("materials", e.target.value)} placeholder="Comma-separated, e.g. recycled aluminium, FSC timber" /></label>{field("Sustainability certifications", "certifications", "text", false, "Comma-separated certifications")}<label className="grid gap-2 text-sm font-bold">Manufacturing or environmental claims<textarea className="input font-normal" value={form.claims} onChange={(e) => update("claims", e.target.value)} placeholder="Describe each claim precisely so validators can assess it." /></label></div>}
      {step === 3 && <div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Product image<div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><input className="block w-full text-xs" type="file" accept="image/*" onChange={(e) => update("imageFilename", e.target.files?.[0]?.name ?? "")} />{form.imageFilename && <p className="mt-3 text-xs text-emerald-700">Selected: {form.imageFilename}</p>}</div></label><label className="grid gap-2 text-sm font-bold">Evidence document<div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><input className="block w-full text-xs" type="file" accept=".pdf,.doc,.docx,.txt" onChange={(e) => update("evidenceFilename", e.target.files?.[0]?.name ?? "")} />{form.evidenceFilename && <p className="mt-3 text-xs text-emerald-700">Selected: {form.evidenceFilename}</p>}</div></label><label className="grid gap-2 text-sm font-bold">Evidence type<select className="input font-normal" value={form.evidenceType} onChange={(e) => update("evidenceType", e.target.value)}><option>Warranty</option><option>Repair policy</option><option>Test report</option><option>Certification</option><option>Parts catalogue</option></select></label>{field("Evidence source URL", "evidenceUrl", "url", false, "https://")}</div>}
      {step === 4 && <div><h3 className="text-xl font-black">Review your submission</h3><p className="mt-2 text-sm text-slate-500">Confirm the information below. You can return to any completed step to edit.</p><dl className="mt-6 grid gap-x-8 gap-y-5 rounded-2xl bg-slate-50 p-6 sm:grid-cols-2">{[["Product", `${form.brand} ${form.name}`], ["Category", form.category], ["Price", form.price ? `$${form.price}` : "Not supplied"], ["Expected lifespan", `${form.lifespan || "—"} years`], ["Warranty", `${form.warranty || "—"} years`], ["Repair service", form.repairAvailable ? "Available" : "Not specified"], ["Replacement parts", form.replacementPartsAvailable ? "Available" : "Not specified"], ["Materials", form.materials || "Not supplied"], ["Evidence", form.evidenceFilename || form.evidenceUrl || "Not supplied"]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl></div>}
    </div>
    <div className="mt-8 flex flex-wrap justify-between gap-3 border-t border-slate-200 pt-6"><button type="button" className="button-secondary" disabled={step === 0} onClick={() => setStep((current) => current - 1)}>← Back</button><div className="flex flex-wrap gap-3">{step === 4 && <button type="button" className="button-secondary" onClick={() => save("draft")}>Save draft</button>}{step < 4 ? <button type="button" className="button-primary" onClick={next}>Continue →</button> : <button type="button" className="button-primary" onClick={() => save("pending")}>Submit product</button>}</div></div>
  </div>;
}
