"use client";

import { useState } from "react";
import ProductSubmissionForm from "@/components/ProductSubmissionForm";
import { useDemo } from "@/components/DemoProvider";
import { AppShell, RoleNotice, StatusBadge, StatusExplanation } from "@/components/ui";

export default function CompanyPage() {
  const { products } = useDemo();
  const [tab, setTab] = useState<"dashboard" | "submit">("dashboard");
  const companyProducts = products.filter((product) => product.company === "Northway Gear Co." || product.company === "Northstar Product Co.");
  const counts = { approved: companyProducts.filter((p) => p.status === "approved").length, pending: companyProducts.filter((p) => p.status === "pending").length, more: companyProducts.filter((p) => p.status === "more_evidence_required").length, rejected: companyProducts.filter((p) => p.status === "rejected").length };

  return <AppShell><section className="border-b border-slate-200 bg-white"><div className="page-shell py-10"><RoleNotice allowed={["company"]}>Company accounts will be required to submit products.</RoleNotice><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Company portal</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Northstar Product Co.</h1><p className="mt-3 text-slate-500">Manage product evidence and track validation outcomes.</p></div><button className="button-primary" onClick={() => setTab("submit")}>+ Submit new product</button></div><div className="mt-8 flex gap-2 border-b border-slate-200"><button onClick={() => setTab("dashboard")} className={`border-b-2 px-4 py-3 text-sm font-bold ${tab === "dashboard" ? "border-emerald-700 text-emerald-800" : "border-transparent text-slate-500"}`}>Dashboard</button><button onClick={() => setTab("submit")} className={`border-b-2 px-4 py-3 text-sm font-bold ${tab === "submit" ? "border-emerald-700 text-emerald-800" : "border-transparent text-slate-500"}`}>Product submission</button></div></div></section>
    <div className="page-shell py-10">{tab === "dashboard" ? <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[[companyProducts.length, "Total submitted", "bg-slate-900 text-white"], [counts.approved, "Approved", "bg-emerald-50 text-emerald-900"], [counts.pending, "Pending", "bg-amber-50 text-amber-900"], [counts.more, "More evidence", "bg-orange-50 text-orange-900"], [counts.rejected, "Rejected", "bg-red-50 text-red-900"]].map(([value, label, tone]) => <div key={String(label)} className={`rounded-2xl p-5 ${tone}`}><strong className="text-3xl">{value}</strong><p className="mt-2 text-sm font-bold opacity-70">{label}</p></div>)}</div><section className="card mt-8 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 p-6"><div><h2 className="text-xl font-black">Submission history</h2><p className="mt-1 text-sm text-slate-500">Statuses include guidance on what happens next.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-4">Product</th><th className="px-6 py-4">Category</th><th className="px-6 py-4">Submitted</th><th className="px-6 py-4">Status & next step</th></tr></thead><tbody>{companyProducts.map((product) => <tr key={product.id} className="border-t border-slate-100"><td className="px-6 py-5"><strong>{product.name}</strong><span className="block text-xs text-slate-500">{product.brand}</span></td><td className="px-6 py-5">{product.category}</td><td className="px-6 py-5">{product.submittedAt ?? "Not submitted"}</td><td className="px-6 py-5"><StatusBadge status={product.status} /><StatusExplanation product={product} /></td></tr>)}</tbody></table></div></section></> : <section className="card mx-auto max-w-5xl p-6 sm:p-9"><div className="mb-8"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">New submission</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em]">Tell us how this product lasts</h2><p className="mt-3 text-sm text-slate-500">All claims should be specific and supported by credible documentation.</p></div><ProductSubmissionForm onComplete={() => setTab("dashboard")} /></section>}</div>
  </AppShell>;
}
